-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 25, 2025 at 03:42 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `article`
--

-- --------------------------------------------------------

--
-- Table structure for table `alembic_version`
--

CREATE TABLE `alembic_version` (
  `version_num` varchar(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `id` int(11) NOT NULL,
  `title` varchar(200) NOT NULL,
  `content` text NOT NULL,
  `category` varchar(100) NOT NULL,
  `created_date` timestamp NULL DEFAULT current_timestamp(),
  `updated_date` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `status` varchar(100) NOT NULL CHECK (`status` in ('Publish','Draft','Trash'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `title`, `content`, `category`, `created_date`, `updated_date`, `status`) VALUES
(1, 'Artikel Pertama', 'Isi artikel', 'Tech', '2025-02-23 13:34:14', '2025-02-23 13:34:14', 'Publish'),
(2, 'belajar backend dengan python untuk pemula', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat API menggunakan Python (Flask) dan mengintegrasikannya dengan frontend yang dibangun menggunakan React. Tutorial ini dilengkapi dengan contoh kode dan penjelasan detail sehingga kamu dapat memahami setiap langkah proses pengembangan Ini adalah konten artikel yang panjangnya minimal 200 karakter. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\" Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat API menggunakan Python (Flask) dan mengintegrasikannya dengan frontend yang dibangun menggunakan React. Tutorial ini dilengkapi dengan contoh kode dan penjelasan detail sehingga kamu dapat memahami setiap langkah proses pengembangan Ini adalah konten artikel yang panjangnya minimal 200 karakter. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\" Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat API menggunakan Python (Flask) dan mengintegrasikannya dengan frontend yang dibangun menggunakan React. Tutorial ini dilengkapi dengan contoh kode dan penjelasan detail sehingga kamu dapat memahami setiap langkah proses pengembangan Ini adalah konten artikel yang panjangnya minimal 200 karakter. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\"', 'teknologi', '2025-02-24 15:18:34', '2025-02-24 15:18:34', 'publish'),
(3, 'belajar fullstack untuk pemula', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat API menggunakan Python (Flask) dan mengintegrasikannya dengan frontend yang dibangun menggunakan React. Tutorial ini dilengkapi dengan contoh kode dan penjelasan detail sehingga kamu dapat memahami setiap langkah proses pengembangan Ini adalah konten artikel yang panjangnya minimal 200 karakter. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\" Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat API menggunakan Python (Flask) dan mengintegrasikannya dengan frontend yang dibangun menggunakan React. Tutorial ini dilengkapi dengan contoh kode dan penjelasan detail sehingga kamu dapat memahami setiap langkah proses pengembangan Ini adalah konten artikel yang panjangnya minimal 200 karakter. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\" Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat API menggunakan Python (Flask) dan mengintegrasikannya dengan frontend yang dibangun menggunakan React. Tutorial ini dilengkapi dengan contoh kode dan penjelasan detail sehingga kamu dapat memahami setiap langkah proses pengembangan Ini adalah konten artikel yang panjangnya minimal 200 karakter. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\"', 'teknologi', '2025-02-24 15:19:51', '2025-02-24 15:19:51', 'publish'),
(4, 'Belajar UI/UX untuk Pemula', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat API menggunakan Python (Flask) dan mengintegrasikannya dengan frontend yang dibangun menggunakan React. Tutorial ini dilengkapi dengan contoh kode dan penjelasan detail sehingga kamu dapat memahami setiap langkah proses pengembangan Ini adalah konten artikel yang panjangnya minimal 200 karakter. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\" Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat API menggunakan Python (Flask) dan mengintegrasikannya dengan frontend yang dibangun menggunakan React. Tutorial ini dilengkapi dengan contoh kode dan penjelasan detail sehingga kamu dapat memahami setiap langkah proses pengembangan Ini adalah konten artikel yang panjangnya minimal 200 karakter. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\" Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat API menggunakan Python (Flask) dan mengintegrasikannya dengan frontend yang dibangun menggunakan React. Tutorial ini dilengkapi dengan contoh kode dan penjelasan detail sehingga kamu dapat memahami setiap langkah proses pengembangan Ini adalah konten artikel yang panjangnya minimal 200 karakter. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\"', 'design', '2025-02-24 15:25:59', '2025-02-24 15:25:59', 'publish'),
(5, 'belajar backend dengan python untuk pemula', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web.\n\nArtikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web', 'Teknologi', '2025-02-25 01:00:39', '2025-02-25 01:00:39', 'publish'),
(6, 'belajar backend untuk pemula menggunakan python dan golang', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web.\n\nArtikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web\n\nArtikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web.\n', 'teknologi', '2025-02-25 01:04:22', '2025-02-25 01:04:40', 'publish'),
(7, 'belajar fullstack untuk pemula edisi terbaru tahun 2025', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web.\n\nArtikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web', 'teknologi', '2025-02-25 01:14:29', '2025-02-25 01:14:39', 'publish'),
(8, 'Belajar UI/UX untuk Pemula edisi tahun 2025', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web.\n\nArtikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web', 'design', '2025-02-25 01:21:47', '2025-02-25 01:21:47', 'publish'),
(9, 'Belajar UI/UX Design untuk Pemula edisi tahun 2025 terbaru', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web.\n\nArtikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web', 'design', '2025-02-25 01:31:44', '2025-02-25 01:32:39', 'publish'),
(10, 'belajar fullstack untuk pemula terbaru edisi ke 1 terbaru tahun 2025', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web.\n\nArtikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web', 'Teknologi', '2025-02-25 01:38:36', '2025-02-25 01:41:07', 'publish'),
(11, 'belajar backend dengan python untuk pemula edisi terbaru ke 2 tahun 2025', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web.\n\nArtikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web', 'teknologi', '2025-02-25 01:49:37', '2025-02-25 01:50:17', 'publish'),
(12, 'belajar UI Design dengan Figma tahun 2024', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web.\n\nArtikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web', 'Design', '2025-02-25 01:54:16', '2025-02-25 01:54:30', 'publish'),
(13, 'Belajar UI Design Menggunakan Framer', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web.\n\nArtikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web', 'design', '2025-02-25 02:03:55', '2025-02-25 02:03:55', 'publish'),
(14, 'belajar html, css dan php edisi terbaru', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web.\n\nArtikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web', 'teknologi', '2025-02-25 02:24:12', '2025-02-25 02:35:11', 'draft'),
(15, 'Belajar Bahasa Inggris untuk Pemula', 'Artikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web.\n\nArtikel ini merupakan panduan lengkap untuk membangun aplikasi fullstack. Di dalam artikel ini, kamu akan belajar cara membuat REST API menggunakan Flask serta mengintegrasikannya dengan frontend React. Tutorial ini disertai contoh kode dan penjelasan langkah demi langkah sehingga kamu dapat memahami konsep dasar dan lanjutan pembuatan aplikasi web modern. Dengan pendekatan praktis ini, kamu akan mendapatkan pengalaman langsung dalam mengembangkan fitur CRUD dan menerapkan validasi data yang sesuai, sekaligus mempelajari best practices dalam pengembangan web', 'Bahasa Indoenesia', '2025-02-25 02:33:44', '2025-02-25 02:34:07', 'trash');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `alembic_version`
--
ALTER TABLE `alembic_version`
  ADD PRIMARY KEY (`version_num`);

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
